# Generated by Django 5.2.5 on 2025-08-13 17:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_sync_field_renames_and_balcony'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complainant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.flat', verbose_name='Квартира, на которую пожаловались'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст жалобы'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='active',
            field=models.BooleanField(db_index=True, verbose_name='Активно ли объявление'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='construction_year',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='Год постройки здания'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда создано объявление'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.CharField(blank=True, max_length=3, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.BooleanField(blank=True, null=True, verbose_name='Наличие балкона'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_flats', to=settings.AUTH_USER_MODEL, verbose_name='Кому понравилось'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='living_area',
            field=models.FloatField(blank=True, null=True, verbose_name='жилая площадь кв.м'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms_number',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='town',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='town_district',
            field=models.CharField(blank=True, max_length=50, verbose_name='Район города'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='owners', to='property.flat', verbose_name='Квартиры'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер владельца'),
        ),
    ]
