# Generated by Django 5.2.5 on 2025-08-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_flat_new_building'),
        ('property', '0014_alter_complaint_complainant_alter_complaint_flat_and_more'),
    ]

    operations = [
    ]
